<a href="https://colab.research.google.com/github/linhlln1104/Mathematics/blob/main/vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import inv, det, matrix_rank, norm

import math

In [ ]:
#vector
#ky hieu bang chu thuong
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

v = v1 + v2
print(v)
v = v1 - v2
print(v)
v = v1 * v2
print(v)
v = v1 / v2
print(v)
v = v1 // v2
print(v)


In [ ]:
#dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a.dot(b)
#c = a1*b1 + a2*b2 + a3*b3

print(c)

#vector-scalar multiplication phep nhan vector-vo huong

d = a * 5
print(d)

In [ ]:
#NORM
a = np.array([1, 2, 3])
print(a)

#L1: tong gia tri tuyet doi cua vector
L1 = norm(a, 1)
print(L1)

#L2: can bac 2 cua tong cac gia tri binh phuong cua vector
L2 = norm(a)
print(L2)

#Max norm: cac gia tri vector lon nhat
Lmax = norm(a, math.inf)
print(Lmax)

In [ ]:
#MATRIX
#Matrix la mot mang 2 chieu cac gia tri vo huong voi mot hoac nhieu cot va dong
#Ky hieu bang chu IN HOA

#matrix 3x3
A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(A)

B = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])
print(B)

C = A + B
print(C)

C = A - B
print(C)

C = A * B
print(C)

C = A / B
print(C)

In [ ]:
#Matrix-Matrix multiplication

A = np.array([[1, 2],[3, 4],[5, 6]])
print(A)



B = np.array([[7, 8], [9, 10]])
print('\n', B)



C = A.dot(B)
print('\n', C)

C = A @ B
print('\n', C)

[[1 2]
 [3 4]
 [5 6]]

 [[ 7  8]
 [ 9 10]]

 [[ 25  28]
 [ 57  64]
 [ 89 100]]

 [[ 25  28]
 [ 57  64]
 [ 89 100]]


In [ ]:
#Matrix-Vector Multiplication

A = np.array([[1, -1],[-1, 3]])
print('\n', A)

v = np.array([2, -1])
print('\n', v)

C = A.dot(v)
print('\n', C)


 [[ 1 -1]
 [-1  3]]

 [ 2 -1]

 [ 3 -5]


In [ ]:
#Matrix-Scalar Multiplication

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

s = 2

C = A.dot(s)
print('\n', C)

C = A * s
print('\n', C)



[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
#Square Matrix - Ma tran vuong - co so dong bang so cot - rows = columns
#Symmetrix Matrix - Ma tran doi xung - co tam giac top-right giong voi tam giac bottom-left
#Triangular Matrix - Ma tran tam giac - La mot Square matrix co tam giac top-right hoac bottom-left co gia tri, phan con lai chua gia tri 0
#Diagonal Matrix - Ma tran duong cheo - La mma tran ma cac gia tri ngoai duong cheo chinh deu = 0
#Identity matrix - La ma tran vuong khong thay doi mot vector khi nhan vector voi ma tran nay. Gia tri tren duong cheo chinh bang 1 con nhung gia tri khac bang 0


In [ ]:
#ma tran chuyen vi(transpose)

A = np.array([[1.0, 2.0],[4.0, 5.0]])
print(A)

N = A.T
print('\n', N)

#ma tran nghich dao(Inverse)
B = inv(A)
print('\n', C)

C = A.dot(B)
print('\n', C)


#trace: tổng các phần tử trên đường chéo chính của ma trận vuông. VD: tr(A), tr(B)\

D = np.array([[1, 5],[2, 4]])
print('\n', D)

E = np.trace(D) #tr(D) = 1 + 4 = 5
print('\n', E)

#Determinant(dinh thuc): Dinh thuc cua ma tran vuong A laf mot gia tri vo huong det(A)

F = det(D)
print('\n', F)

#Rank(hang ma tran): La uoc tinh so luong hang hoac cot doc lap tuyen tinh trong ma tran

G = 

[[1. 2.]
 [4. 5.]]

 [[1. 4.]
 [2. 5.]]

 [[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]

 [[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]

 [[1 5]
 [2 4]]

 5

 -6.0
